configuration:
  swagger:
    app: 'Event Management App'
    description: 'Web app for managing events in a certain city/country.'
    developer: 'Benjamin Peljto'
    email: 'benjamin.peljto@stu.ibu.edu.ba'


spring:
  data:
    mongodb:
      database: eventifydb
      uri: mongodb+srv://benjaminpeljto:w9FIoVs1dyDR966E@cluster0.27e6rwe.mongodb.net/?retryWrites=true&w=majority
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'benjaminpeljto00@gmail.com'
    password: 'aieu lzsi ugqi mppx'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandbox93d2af94da984fd88d2b981c38eb27be.mailgun.org
    from-email: Eventify <mailgun@sandbox93d2af94da984fd88d2b981c38eb27be.mailgun.org>
    username: api
    password: 3ff06f4f0e707dcc89d8d4dbb97ca952-1c7e8847-3b7b41f3

security:
  jwt:
    secret: '11af9ed3fdc7354ff722f1b30d782bc220758adf1f6658931873e2683f1f7d8c'


qr:
  temp-directory: src/main/java/ba/ibu/edu/web_engineering_project/api/impl/qr/temp

auth:
  confirmation-link: http://localhost:8000/api/auth/confirm?verification=

aws:
  lambda:
    email-confirmation-lambda: https://f75k5m2ygpvw6bjzeqfi33nicm0vpqve.lambda-url.eu-central-1.on.aws/
    generate-send-tickets-lambda: https://hf32xmiz5ibbvgeqokihzajvoy0dvini.lambda-url.eu-central-1.on.aws/
  credentials:
    access-key: AKIA3SXL3DGQDIYPEDMS
    secret-key: 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
  region:
    static: eu-central-1
  stack:
    auto: false
  bucket:
    name: event-management-university-project
